spring:
  application:
    name: javafx-app
  sql:
    init:
      schema-locations: schema/schema-batch.sql
      mode: always
  h2:
    console:
      settings:
        trace: true
  datasource:
    url: jdbc:h2:file:/home/ae/Downloads/upwork/temperature;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: pass@word
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  batch:
    jdbc:
      initialize-schema: always
      platform: h2
    job:
      enabled: true


logging:
  level:
    org:
      springframework:
        batch: DEBUG